# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            'Photographer'
tagline:          'ZSM'
description:      'Photo by ZSM'
url:              http://photozsm.github.io

author:
  name:           'ZSM.'
  url:            

paginate:         1

# Custom vars
version:          2.0.0


